const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={screen:0,clues:0,sound:true,pendingNext:0,advanceAfterBoard:false,answerTurn:0,lastCorrectSlot:-1,memory:0,scanFound:new Set(),scanCurrent:null,db:0,dbCurrent:null,dbScore:0,dbSolved:new Set(),map:0,mapCurrent:null,mapRoute:null,mapHistory:[],glitch:0,glitchDanger:0,excluded:new Set(),selected:null};
const clues=['THE PERSON IS NEXT TO THE WINDOW.','THE PERSON LIKES BANANAS.','THE PERSON HAS GOT A CAT.','THE PERSON CAN RIDE A BIKE.'];
const people=[
 {name:'MILO',traits:['has got a dog','likes pizza','can swim'],pos:'p1',pronoun:'HIM'},
 {name:'ZOE',traits:['has got a cat','likes bananas','can ride a bike'],pos:'p2',pronoun:'HER'},
 {name:'BEN',traits:['has got a fish','likes burgers','can play football'],pos:'p3',pronoun:'HIM'},
 {name:'LUCY',traits:['has got a cat','likes apples','can swim'],pos:'p4',pronoun:'HER'}];
const memory=[
 {q:'Where is the blue book?',a:['ON THE TABLE','UNDER THE CHAIR','NEXT TO THE WINDOW'],ok:0},
 {q:'What is under the table?',a:['A CAT','A BALL','A TOY BOX'],ok:1},
 {q:'What colour is the chair?',a:['BLUE','YELLOW','RED'],ok:2},
 {q:'Is there a cat behind the chair?',a:['YES','NO'],ok:0}];
const scans=[
 {name:'BALL',a:['A BALL','A MOON','AN ORANGE'],ok:0,x:27,y:43},
 {name:'BOOK',a:['A BOX','A BOOK','A TABLET'],ok:1,x:47,y:45},
 {name:'BANANA',a:['A CAMERA','A BANANA','A SHOE'],ok:1,x:66,y:40},
 {name:'CAMERA',a:['A CAMERA','A RADIO','A CLOCK'],ok:0,x:31,y:67},
 {name:'ROBOT',a:['A ROBOT','A DOLL','A MONSTER'],ok:0,x:62,y:67}];
const dbTasks=[
 {person:0,fact:0,q:"CHECK MILO'S PET",context:"Milo says: 'My pet can run. It can't fly and it can't swim.'",a:['A DOG','A BIRD','A FISH'],ok:0},
 {person:0,fact:1,q:"CHECK MILO'S LUNCH",context:"Milo has got cheese, tomato and bread. What does he make?",a:['PIZZA','SOUP','ICE CREAM'],ok:0},
 {person:0,fact:2,q:"CHECK MILO'S CLUB",context:"Milo is in the pool. Complete his answer: 'Yes, I ___." ,a:['CAN SWIM','CAN FLY','HAVE SWIM'],ok:0},
 {person:1,fact:0,q:"CHECK ZOE'S PET",context:"Zoe says: 'It is small. It has got four legs. It says meow.'",a:['A CAT','A FISH','A BIRD'],ok:0},
 {person:1,fact:1,q:"CHECK ZOE'S SNACK",context:"Zoe chooses the long yellow fruit. What does she like?",a:['BANANAS','APPLES','CARROTS'],ok:0},
 {person:1,fact:2,q:"CHECK ZOE'S JOURNEY",context:"Zoe is on a bike. What can she do?",a:['RIDE A BIKE','PLAY THE PIANO','SWIM'],ok:0},
 {person:2,fact:0,q:"CHECK BEN'S PET",context:"Ben says: 'My pet lives in water. It hasn't got legs.'",a:['A FISH','A DOG','A CAT'],ok:0},
 {person:2,fact:1,q:"CHECK BEN'S LUNCH",context:"Ben likes burgers. What food does he like?",a:['A BURGER','A BANANA','A CAKE'],ok:0},
 {person:2,fact:2,q:"CHECK BEN'S TEAM",context:"Ben plays football. What can he do?",a:['PLAY FOOTBALL','RIDE A BIKE','PLAY THE GUITAR'],ok:0},
 {person:3,fact:0,q:"CHECK LUCY'S PET",context:"Lucy says: 'It sleeps on my chair and it likes milk.'",a:['A CAT','A FISH','A HORSE'],ok:0},
 {person:3,fact:1,q:"CHECK LUCY'S SNACK",context:"Lucy's fruit is red or green. It grows on a tree.",a:['APPLES','BANANAS','POTATOES'],ok:0},
 {person:3,fact:2,q:"CHECK LUCY'S CLUB",context:"Lucy is in the water. She has got goggles. What can she do?",a:['SWIM','FLY','SKATE'],ok:0}];
const rooms=[
 {name:'CLASSROOM',pos:'0% 0%',x:10,y:18},{name:'PLAYROOM',pos:'50% 0%',x:38,y:11},{name:'LIBRARY',pos:'100% 0%',x:69,y:15},
 {name:'GARDEN',pos:'0% 100%',x:9,y:66},{name:'KITCHEN',pos:'50% 100%',x:61,y:84},{name:'MUSIC ROOM',pos:'100% 100%',x:90,y:67},
 {name:'ART ROOM',pos:'0% 50%',x:37,y:54,extra:true},{name:'HALL',pos:'50% 50%',x:92,y:28,extra:true},{name:'GYM',pos:'100% 50%',x:36,y:88,extra:true}];
const mapTasks=[
 {q:'START WHERE THERE ARE TWO WINDOWS AND A BLUE DESK.',ok:0},
 {q:'NEXT: FIND A RED CHAIR AND A TOY TRAIN.',ok:1},
 {q:'GO TO THE PLACE WITH A GREEN TABLE AND MANY BOOKS.',ok:2},
 {q:'FOLLOW THE TRACK TO A BALL NEAR A BICYCLE.',ok:3},
 {q:'FIND THREE BLUE CUPS AND SOME BANANAS.',ok:4},
 {q:'THE LAST PLACE HAS A PIANO AND A DRUM.',ok:5}];
mapTasks.push(
 {q:'FIND PAINT AND PICTURES.',ok:6},
 {q:'GO TO THE PLACE WITH MANY DOORS AND A CLOCK.',ok:7},
 {q:'FIND THE ROOM WITH A BALL AND A BASKET.',ok:8});
const glitchTasks=[
 {q:'Build the question.',tokens:['swim?','Can','he'],answer:['Can','he','swim?']},
 {q:'Build the sentence.',tokens:['a cat.','has got','She'],answer:['She','has got','a cat.']},
 {q:'Build the sentence.',tokens:['under','The ball','the table.','is'],answer:['The ball','is','under','the table.']},
 {q:'Build the question.',tokens:['a bike?','ride','Can','he'],answer:['Can','he','ride','a bike?']}];
const iceTasks=[
 {label:'WHEEL 1 · HELLO',title:'ONLY ONE IS TRUE',prompt:'👋 Say your name to a partner. Then find the only correct example.',button:'SHOW 4 EXAMPLES'},
 {label:'WHEEL 2 · WORDS',title:'ODD ONE OUT',prompt:'🔎 Find one odd picture. Five rounds — one hides a number.',button:'START 5 ROUNDS'},
 {label:'WHEEL 3 · LISTENING',title:'ROBOT SAYS',prompt:'🔊 Listen. Touch three pictures in the same order.',button:'START LISTENING'},
 {label:'WHEEL 4 · PACK THE BAG',title:'WHAT GOES IN THE BAG?',prompt:'🎒 Look at the picture clue. Pack only three correct things.',button:'OPEN THE BAG'}];

function beep(good=true){if(!state.sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=good?620:180;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}}
function showScreen(n){state.screen=n;$$('.screen').forEach((s,i)=>s.classList.toggle('active',i===n));document.body.classList.toggle('before-case',n===0);scrollTo({top:0});if(n===2)startMemory();if(n===3)renderScan();if(n===4)renderDatabase();if(n===5){if(!state.mapRoute)state.mapRoute=[0,...[1,2,3,4,5,6,7,8].sort(()=>Math.random()-.5).slice(0,4)];renderMap()}if(n===6)renderGlitch();if(n===7)renderFinal();if(n===8)celebrate()}
$$('[data-next]').forEach(b=>b.onclick=()=>showScreen(state.screen+1));$$('[data-go]').forEach(b=>b.onclick=()=>showScreen(+b.dataset.go));
$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'SOUND ON':'SOUND OFF';beep()};
function setAnswers(box,items,ok,onDone,onWrong=()=>{}){let slot;do{slot=Math.floor(Math.random()*items.length)}while(items.length>1&&slot===state.lastCorrectSlot);state.lastCorrectSlot=slot;const correct={text:items[ok],i:ok},wrong=items.map((text,i)=>({text,i})).filter(x=>x.i!==ok).sort(()=>Math.random()-.5),mixed=[...wrong];mixed.splice(slot,0,correct);box.innerHTML=mixed.map(x=>`<button class="answer-btn" data-i="${x.i}">${x.text}</button>`).join('');$$('.answer-btn',box).forEach(b=>b.onclick=()=>{const right=+b.dataset.i===ok;beep(right);b.classList.add(right?'correct':'wrong');if(right){$$('.answer-btn',box).forEach(x=>x.disabled=true);onDone(b)}else{onWrong(b);b.classList.add('shake');setTimeout(()=>{b.classList.remove('shake');b.classList.remove('wrong')},350)}})}
function startMemory(){state.memory=0;$('#memoryView').classList.remove('hidden');$('#memoryQuiz').classList.add('hidden');$('#memoryNext').classList.add('hidden');let t=12;$('#lookTimer').textContent=t;clearInterval(window.lookClock);window.lookClock=setInterval(()=>{t--;$('#lookTimer').textContent=t;if(t<=0){clearInterval(window.lookClock);showMemoryQuestion()}},1000)}
function showMemoryQuestion(){$('#memoryView').classList.add('hidden');$('#memoryQuiz').classList.remove('hidden');const x=memory[state.memory];$('#memoryCount').textContent=`QUESTION ${state.memory+1} OF ${memory.length}`;$('#memoryQuestion').textContent=x.q;$('#memoryFeedback').textContent='';setAnswers($('#memoryAnswers'),x.a,x.ok,()=>{$('#memoryFeedback').textContent='Good detective work!';setTimeout(()=>{state.memory++;if(state.memory<memory.length)showMemoryQuestion();else $('#memoryNext').classList.remove('hidden')},700)})}
let lights=2;$('#lightsBtn').onclick=()=>{if(lights<1)return;lights--;$('#lightsBtn small').textContent=`${lights} left`;$('#memoryView').classList.remove('hidden');$('#memoryQuiz').classList.add('hidden');setTimeout(()=>{if(state.memory<memory.length)showMemoryQuestion()},3500)};$('#memoryNext').onclick=()=>awardClue(0,3);
function renderScan(){const scanner=$('#scanner'),lens=$('#scanLens'),hotspots=$('#scanHotspots');$('#scanNum').textContent=state.scanFound.size;$('#scanNext').classList.toggle('hidden',state.scanFound.size<scans.length);hotspots.innerHTML=scans.map((x,i)=>state.scanFound.has(i)?'':`<i class="scan-target" style="left:${x.x}%;top:${x.y}%"></i>`).join('');$('#scanTray').innerHTML=[...state.scanFound].map(i=>`<article style="background-position:${scans[i].x}% ${scans[i].y}%"><b>${scans[i].name}</b></article>`).join('')||'<span>EMPTY</span>';if(!scanner.dataset.ready){const move=e=>{const r=scanner.getBoundingClientRect(),x=Math.max(0,Math.min(r.width,e.clientX-r.left)),y=Math.max(0,Math.min(r.height,e.clientY-r.top));lens.style.left=x+'px';lens.style.top=y+'px';lens.style.backgroundSize=`${r.width}px ${r.height}px`;lens.style.backgroundPosition=`${-x+55}px ${-y+55}px`};scanner.onpointermove=move;scanner.onpointerenter=()=>lens.classList.add('active');scanner.onpointerleave=()=>lens.classList.remove('active');scanner.onclick=e=>{const r=scanner.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*100,py=(e.clientY-r.top)/r.height*100,candidates=scans.map((s,i)=>({i,d:Math.hypot((s.x-px)*1.4,s.y-py)})).filter(x=>!state.scanFound.has(x.i)).sort((a,b)=>a.d-b.d);if(candidates[0]&&candidates[0].d<9)openScan(candidates[0].i);else $('#scanFeedback').textContent='Only static here. Move the scanner and try another spot.'};scanner.dataset.ready='1'}if(state.scanFound.size===0){$('#scanQuestion').textContent='Find a shape. Tap it.';$('#scanAnswers').classList.add('hidden')}}
function openScan(i){if(state.scanFound.has(i))return;state.scanCurrent=i;const x=scans[i];$('#scanQuestion').textContent='WHAT IS THIS OBJECT?';$('#scanFeedback').textContent='';$('#scanAnswers').classList.remove('hidden');setAnswers($('#scanAnswers'),x.a,x.ok,()=>{state.scanFound.add(i);$('#scanFeedback').textContent=`${x.name}. EVIDENCE TAG READY.`;setTimeout(()=>{renderScan();if(state.scanFound.size<5)$('#scanQuestion').textContent='Find another shape.'},700)},()=>$('#scanFeedback').textContent='Move the scanner and look again.')}
$('#scanNext').onclick=()=>awardClue(1,4);
function openPortrait(i,checked=3){const p=people[i];$('#bigPortrait').className=`big-portrait ${p.pos}`;$('#bigName').textContent=p.name;$('#bigTraits').innerHTML=p.traits.map((t,n)=>`<span>${n<checked?t:'CHECK THE STORY'}</span>`).join('');$('#portraitModal').classList.remove('hidden')}
function cardHTML(p,i,checked=0){return `<article class="suspect-card ${checked<3?'locked':''}"><button class="portrait ${p.pos}" data-zoom="${i}" data-checked="${checked}" aria-label="Look closely at ${p.name}"><i class="zoom-lens"></i></button><div><h3>${p.name}</h3><small class="fact-count">${checked} / 3 FACTS</small><div class="traits">${p.traits.map((t,n)=>`<span class="${n<checked?'fact-open':''}">${n<checked?t:'CHECK THE STORY'}</span>`).join('')}</div></div></article>`}
function bindZoom(){$$('[data-zoom]').forEach(b=>b.onclick=e=>{e.stopPropagation();openPortrait(+b.dataset.zoom,b.dataset.checked===undefined?3:+b.dataset.checked)})}
function renderDatabase(){const checked=people.map((_,person)=>dbTasks.filter((x,i)=>x.person===person&&state.dbSolved.has(i)).length);$('#suspectCards').innerHTML=people.map((p,i)=>cardHTML(p,i,checked[i])).join('');bindZoom();$('#taskDots').innerHTML=dbTasks.map((_,i)=>`<i class="${state.dbSolved.has(i)?'done':''}"></i>`).join('');$('#interviewContinue').classList.add('hidden');$('#dbFeedback').textContent='';if(state.dbSolved.size>=dbTasks.length){$('#interviewLabel').textContent=`BOARD COMPLETE · SCORE ${state.dbScore}`;$('#dbQuestion').textContent='ALL 12 FILES ARE OPEN!';$('#dbContext').textContent='Every suspect profile is ready for the final deduction.';$('#dbAnswers').innerHTML='';$('#dbNext').classList.remove('hidden');return}if(state.dbCurrent===null){$('#interviewLabel').textContent=`CHOOSE A CASE CARD · SCORE ${state.dbScore}`;$('#dbQuestion').textContent='PICK ANY NUMBER';$('#dbContext').textContent='A question and a surprise score are hiding behind every card.';$('#dbAnswers').innerHTML=`<div class="bamboozle-board">${dbTasks.map((_,i)=>`<button data-case="${i}" ${state.dbSolved.has(i)?'disabled':''}>${state.dbSolved.has(i)?'✓':i+1}</button>`).join('')}</div>`;$$('[data-case]',$('#dbAnswers')).forEach(b=>b.onclick=()=>{state.dbCurrent=+b.dataset.case;renderDatabase()});return}const x=dbTasks[state.dbCurrent];$('#interviewLabel').textContent=`CASE CARD ${String(state.dbCurrent+1).padStart(2,'0')} · ${people[x.person].name}`;$('#dbQuestion').textContent=x.q;$('#dbContext').textContent=x.context;setAnswers($('#dbAnswers'),x.a,x.ok,()=>{const rewards=[10,10,20,20,30,50],reward=rewards[Math.floor(Math.random()*rewards.length)];state.dbScore+=reward;$('#dbFeedback').innerHTML=`<div class="reward-card"><b>+${reward}</b><span>FACT FOUND!</span></div>`;$('#interviewContinue').textContent='BACK TO THE BOARD →';$('#interviewContinue').classList.remove('hidden');$$('.answer-btn',$('#dbAnswers')).forEach(b=>b.disabled=true)})}$('#interviewContinue').onclick=()=>{state.dbSolved.add(state.dbCurrent);state.db=state.dbSolved.size;state.dbCurrent=null;renderDatabase()};$('#dbNext').onclick=()=>awardClue(2,4);
function renderFootprints(){const trail=$('#footprintTrail');trail.innerHTML='';for(let n=1;n<state.mapHistory.length;n++){const a=rooms[state.mapHistory[n-1]],b=rooms[state.mapHistory[n]],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx*12,dy*7),steps=Math.max(2,Math.floor(d/38)),angle=Math.atan2(dy*7,dx*12)*180/Math.PI;for(let k=1;k<steps;k++){const foot=document.createElement('i'),t=k/steps;foot.style.left=`${a.x+dx*t}%`;foot.style.top=`${a.y+dy*t}%`;foot.style.transform=`translate(-50%,-50%) rotate(${angle+90}deg) translateX(${k%2?'-7px':'7px'})`;trail.append(foot)}}}
function renderMap(){const map=$('#roomMap');map.querySelectorAll('.room').forEach(x=>x.remove());rooms.forEach((r,i)=>{const b=document.createElement('button');b.className='room map-node';b.setAttribute('aria-label',`Open ${r.name}`);b.style.left=r.x+'%';b.style.top=r.y+'%';b.style.backgroundImage=`url('assets/${r.extra?'map-locations-extra':'map-locations'}.png')`;b.style.backgroundSize=r.extra?'300% 100%':'300% 200%';b.style.backgroundPosition=r.pos;b.dataset.room=i;b.onclick=()=>openLocation(i);map.append(b)});const target=state.mapRoute?.[state.map];$('#mapQuestion').textContent=target===undefined?'THE ROUTE IS COMPLETE!':mapTasks[target].q;$('#trailCount').textContent=`${state.map} / 5`;renderFootprints();if(state.map>=5)$('#mapNext').classList.remove('hidden')}
function openLocation(i){state.mapCurrent=i;const r=rooms[i],big=$('#bigLocation');big.style.backgroundImage=`url('assets/${r.extra?'map-locations-extra':'map-locations'}.png')`;big.style.backgroundSize=r.extra?'300% 100%':'300% 200%';big.style.backgroundPosition=r.pos;$('#locationName').textContent=r.name;$('#locationModal').classList.remove('hidden')}
function chooseRoom(i){if(state.map>=5)return;const right=i===state.mapRoute[state.map];beep(right);if(!right){$('#mapFeedback').textContent='Not this place. Inspect another location.';$('#locationModal').classList.add('hidden');return}const r=rooms[i],pawn=$('#detectivePawn');state.mapHistory.push(i);pawn.style.left=r.x+'%';pawn.style.top=r.y+'%';pawn.classList.add('walking');setTimeout(()=>pawn.classList.remove('walking'),900);$('#locationModal').classList.add('hidden');$('#mapFeedback').textContent=state.map===4?'A broken camera file is here.':`The route now reaches ${r.name.toLowerCase()}.`;state.map++;setTimeout(renderMap,900)}
$('#chooseLocation').onclick=()=>chooseRoom(state.mapCurrent);$('#closeLocation').onclick=()=>$('#locationModal').classList.add('hidden');$('#locationModal').onclick=e=>{if(e.target===$('#locationModal'))$('#locationModal').classList.add('hidden')};$('#mapNext').onclick=()=>showScreen(6);
function updateMonster(){const scale=Math.max(.42,.72-state.glitch*.09+state.glitchDanger*.16);$('#monster').style.setProperty('--scale',scale);$('#distanceLabel').textContent=state.glitchDanger>=2?'VERY CLOSE':state.glitchDanger===1?'CLOSER':state.glitch>=2?'FAR AWAY':'FAR';$('#glitchMeter').style.width=`${state.glitch/glitchTasks.length*100}%`}
function renderGlitch(){$$('#cctvRecovery i').forEach((tile,i)=>tile.classList.toggle('clear',i<state.glitch));$('.glitch-field').classList.toggle('file-ready',state.glitch>=glitchTasks.length);if(state.glitch>=glitchTasks.length){$('#glitchQuestion').textContent='THE PHOTO IS CLEAR. WHAT CAN YOU SEE?';$('#glitchAnswers').innerHTML='';$('#glitchFeedback').textContent='A bicycle. A helmet with a banana. Part of the backpack.';$('#monster').classList.add('glitch-gone');$('#glitchNext').classList.remove('hidden');$('#glitchMeter').style.width='100%';return}const x=glitchTasks[state.glitch],built=[];$('#glitchQuestion').textContent=x.q;$('#glitchFeedback').innerHTML='<div class="sentence-line" id="sentenceLine">?</div><small>Capital letter first. Punctuation last.</small>';$('#glitchAnswers').innerHTML=x.tokens.map((word,i)=>`<button class="word-tile" data-word="${i}">${word}</button>`).join('');updateMonster();$$('.word-tile',$('#glitchAnswers')).forEach(b=>b.onclick=()=>{built.push(x.tokens[+b.dataset.word]);b.disabled=true;b.classList.add('used');$('#sentenceLine').textContent=built.join(' ');if(built.length===x.answer.length){if(built.join('|')===x.answer.join('|')){$('#sentenceLine').classList.add('correct');state.glitch++;state.glitchDanger=Math.max(0,state.glitchDanger-1);beep();setTimeout(renderGlitch,700)}else{$('#sentenceLine').classList.add('wrong');state.glitchDanger=Math.min(2,state.glitchDanger+1);beep(false);setTimeout(renderGlitch,700)}}})}$('#glitchNext').onclick=()=>awardClue(3,6);
function renderBoard(){$('#boardCount').textContent=`${state.clues} / 4`;$('#boardStatus').textContent=state.clues===4?'READY FOR THE FINAL DEDUCTION':`${4-state.clues} CLUES TO FIND`;$('#boardClues').innerHTML=clues.map((clue,i)=>`<article class="board-clue c${i+1} ${i<state.clues?'pinned':'locked'}">${i===3&&i<state.clues?'<img src="assets/camera-photo.png" alt="Camera evidence">':''}<small>CLUE ${i+1}</small><b>${i<state.clues?clue:'?'}</b></article>`).join('')}
function awardClue(index,next){state.clues=Math.max(state.clues,index+1);$('#progressText').textContent=`CLUES: ${state.clues} / 4`;$('#progressFill').style.width=`${state.clues*25}%`;$('#clueNumber').textContent=`CLUE #${index+1}`;$('#clueText').textContent=clues[index];state.pendingNext=next;renderBoard();$('#clueModal').classList.remove('hidden');beep()}$('#keepClue').onclick=()=>{$('#clueModal').classList.add('hidden');state.advanceAfterBoard=true;$('#caseBoard').classList.remove('hidden')};$('#closeClue').onclick=()=>$('#keepClue').click();
function renderFinal(){$('#clueStrip').innerHTML=clues.map((c,i)=>`<div class="mini-clue"><small>CLUE ${i+1}</small>${c.replace('THE PERSON ','')}</div>`).join('');$('#finalSuspects').innerHTML=people.map((p,i)=>`<article class="final-card ${state.excluded.has(i)?'excluded':''} ${state.selected===i?'selected':''}" data-i="${i}" data-not="NOT ${p.pronoun}"><button class="portrait ${p.pos}" data-zoom="${i}" aria-label="Look closely at ${p.name}"><i class="zoom-lens"></i></button><h3>${p.name}</h3><div class="final-traits">${p.traits.map(t=>`<span>${t}</span>`).join('')}</div><div class="deduction-actions"><button class="mark-btn" data-mark="${i}">${state.excluded.has(i)?'PUT BACK':'NOT '+p.pronoun}</button><button class="choose-btn" data-choose="${i}">CHOOSE</button></div></article>`).join('');bindZoom();$$('[data-mark]').forEach(b=>b.onclick=()=>{const i=+b.dataset.mark;if(state.excluded.has(i))state.excluded.delete(i);else{state.excluded.add(i);if(state.selected===i)state.selected=null}renderFinal()});$$('[data-choose]').forEach(b=>b.onclick=()=>{const i=+b.dataset.choose;if(state.excluded.has(i))state.excluded.delete(i);state.selected=i;renderFinal()});$('#accuseBtn').disabled=state.selected===null}
$('#resetMarks').onclick=()=>{state.excluded.clear();state.selected=null;renderFinal()};$('#accuseBtn').onclick=()=>{if(state.selected===1)showScreen(8);else{beep(false);$('.final-card.selected').classList.add('shake');setTimeout(()=>$('.final-card.selected')?.classList.remove('shake'),400)}};
function celebrate(){const colors=['#f5b942','#34d6cb','#ef6a5b','#fff'];$('#confetti').innerHTML=Array.from({length:35},(_,i)=>`<span style="left:${Math.random()*100}%;background:${colors[i%4]};animation-delay:${Math.random()*3}s"></span>`).join('');beep()}
$('#playAgain').onclick=()=>location.reload();
$('#closePortrait').onclick=()=>$('#portraitModal').classList.add('hidden');$('#portraitModal').onclick=e=>{if(e.target===$('#portraitModal'))$('#portraitModal').classList.add('hidden')};
$('#boardBtn').onclick=()=>{state.advanceAfterBoard=false;renderBoard();$('#caseBoard').classList.remove('hidden')};$('#closeBoard').onclick=()=>{$('#caseBoard').classList.add('hidden');if(state.advanceAfterBoard){state.advanceAfterBoard=false;showScreen(state.pendingNext)}};$('#caseBoard').onclick=e=>{if(e.target===$('#caseBoard'))$('#closeBoard').click()};renderBoard();

// The locked-door ice-breaker comes before the investigation.
$('#dbNext').onclick=()=>awardClue(2,5);
$('#glitchNext').onclick=()=>awardClue(3,7);
let iceStep=0;
function renderIce(){const x=iceTasks[iceStep];$$('#iceProgress i').forEach((dot,i)=>dot.classList.toggle('done',i<iceStep));$('#iceLabel').textContent=x.label;$('#iceTitle').textContent=x.title;$('#icePrompt').textContent=x.prompt;$('#iceDone').textContent=x.button;$('#iceDone').classList.remove('hidden');$('#clueStamp').classList.add('hidden');$('#iceGame').innerHTML='';$('#iceFeedback').textContent=''}
function solveWheel(digit){$('#iceGame').innerHTML='';$('#iceFeedback').textContent='';$('#clueStamp>span').textContent=digit;$('#clueStamp').classList.remove('hidden');beep()}
function bindPuzzle(ok,digit){$$('#iceGame [data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer===ok){b.classList.add('correct');setTimeout(()=>solveWheel(digit),500)}else{b.classList.add('wrong');beep(false);setTimeout(()=>b.classList.remove('wrong'),400)}})}
function speakClue(text){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices();utterance.voice=voices.find(v=>v.lang.startsWith('en-GB'))||voices.find(v=>v.lang.startsWith('en'))||null;utterance.lang='en-GB';utterance.rate=.82;utterance.pitch=1.05;speechSynthesis.speak(utterance)}
function startIceGame(){const game=$('#iceGame');$('#iceDone').classList.add('hidden');if(iceStep===0){game.innerHTML='<div class="number-puzzle four"><button data-answer="no">3 + 2 = 6</button><button data-answer="yes">2 + 5 = 7</button><button data-answer="no">4 + 4 = 9</button><button data-answer="no">6 − 2 = 5</button></div>';bindPuzzle('yes','7')}
 if(iceStep===1){const rounds=[{items:[['🐱','CAT'],['🐶','DOG'],['🍌','BANANA'],['🐟','FISH']],odd:2},{items:[['🖊️','PEN'],['📘','BOOK'],['⚽','FOOTBALL'],['📏','RULER']],odd:2},{items:[['🐱','CAT'],['0','ZERO'],['🐶','DOG'],['🐟','FISH']],odd:1},{items:[['🏊','SWIM'],['🏃','RUN'],['🍎','APPLE'],['⚽','PLAY FOOTBALL']],odd:2},{items:[['🍌','BANANA'],['📘','BOOK'],['🍎','APPLE'],['🍊','ORANGE']],odd:1}];let round=0;const showRound=()=>{const x=rounds[round];game.innerHTML=`<div class="odd-round"><b>ROUND ${round+1} / 5</b><div>${x.items.map((item,i)=>`<button data-i="${i}"><span>${item[0]}</span><small>${item[1]}</small></button>`).join('')}</div></div>`;$$('.odd-round button',game).forEach(b=>b.onclick=()=>{if(+b.dataset.i===x.odd){b.classList.add('correct');round++;beep();if(round===5)setTimeout(()=>solveWheel('0'),450);else setTimeout(showRound,450)}else{b.classList.add('wrong');beep(false);setTimeout(()=>b.classList.remove('wrong'),350)}})};showRound()}
 if(iceStep===2){game.innerHTML='<button class="listen-btn" id="playRobot">▶ PLAY NOW</button><div class="listening-grid"><button data-object="cat">🐱</button><button data-object="ball">⚽</button><button data-object="bike">🚲</button><button data-object="book">📘</button><button data-object="banana">🍌</button><button data-object="dog">🐶</button></div><div class="listen-slots"><i></i><i></i><i></i></div>';const order=['cat','bike','banana'];let heard=[];$('#playRobot').onclick=()=>speakClue('Touch the cat. Then touch the bike. Then touch the banana.');$$('.listening-grid button').forEach(b=>b.onclick=()=>{heard.push(b.dataset.object);b.classList.add('chosen');$$('.listen-slots i')[heard.length-1]?.classList.add('filled');if(heard.length===3){if(heard.join()==order.join()){setTimeout(()=>solveWheel('9'),350)}else{heard=[];$$('.listening-grid button').forEach(x=>x.classList.remove('chosen'));$$('.listen-slots i').forEach(x=>x.classList.remove('filled'));$('#iceFeedback').textContent='Listen again.';beep(false)}}})}
 if(iceStep===3){game.innerHTML='<div class="packing-clue"><b>PACK:</b><span>📘</span><span>🖊️</span><span>🍎</span></div><div class="packing-game"><div class="packing-items"><button data-item="book">📘</button><button data-item="ball">⚽</button><button data-item="pen">🖊️</button><button data-item="cat">🐱</button><button data-item="apple">🍎</button><button data-item="bike">🚲</button></div><div class="school-bag">🎒<i></i><i></i><i></i></div></div>';const wanted=['book','pen','apple'],packed=[];$$('.packing-items button',game).forEach(b=>b.onclick=()=>{if(wanted.includes(b.dataset.item)&&!packed.includes(b.dataset.item)){packed.push(b.dataset.item);b.classList.add('packed');$$('.school-bag i')[packed.length-1].classList.add('filled');beep();if(packed.length===3)setTimeout(()=>solveWheel('2'),500)}else{b.classList.add('wrong');beep(false);setTimeout(()=>b.classList.remove('wrong'),350)}})}}
$('#iceDone').onclick=startIceGame;
$('#keepDigit').onclick=()=>{iceStep++;if(iceStep<iceTasks.length)renderIce();else{$('#iceProgress').classList.add('hidden');$('.ice-card').classList.add('hidden');$('#doorLock').classList.remove('hidden');renderWheels()}};
const wheelValues=[0,0,0,0];
function renderWheels(){$('#numberWheels').innerHTML=wheelValues.map((n,i)=>`<div class="number-wheel"><button data-wheel="${i}" data-dir="1">▲</button><strong>${n}</strong><button data-wheel="${i}" data-dir="-1">▼</button></div>`).join('');$$('#numberWheels button').forEach(b=>b.onclick=()=>{const i=+b.dataset.wheel;wheelValues[i]=(wheelValues[i]+ +b.dataset.dir+10)%10;b.parentElement.classList.add('spinning');beep();setTimeout(()=>{renderWheels()},180)})}
$('#unlockDoor').onclick=()=>{const code=wheelValues.join('');if(code==='7092'){$('#lockFeedback').textContent='ACCESS GRANTED · THE DOOR IS OPEN';$('#doorLock').classList.add('unlocked');$('#lockHero').classList.add('is-open');beep();setTimeout(()=>showScreen(1),2200)}else{$('#lockFeedback').textContent='THE LOCK IS STILL CLOSED. CHECK YOUR CLUES.';$('#doorLock').classList.add('shake');beep(false);setTimeout(()=>$('#doorLock').classList.remove('shake'),400)}};
document.body.classList.add('before-case');renderIce();
