const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={screen:0,clues:0,sound:true,pendingNext:0,advanceAfterBoard:false,answerTurn:0,memory:0,scanFound:new Set(),scanCurrent:null,db:0,map:0,mapCurrent:null,mapRoute:null,mapHistory:[],glitch:0,glitchDanger:0,excluded:new Set(),selected:null,boardSelected:null,connections:new Set(),ruled:new Set(),inspectFound:false,revealStep:0};
const clues=['THE PERSON IS NEAR THE WINDOW.','THE PERSON LIKES BANANAS.','THE PERSON HAS GOT A CAT.','THE PERSON CAN RIDE A BIKE.'];
const people=[
 {name:'MILO',traits:['has got a dog','likes pizza','can swim'],last:'near the door',pos:'p1',pronoun:'HIM'},
 {name:'ZOE',traits:['has got a cat','likes bananas','can ride a bike'],last:'near the window',pos:'p2',pronoun:'HER'},
 {name:'BEN',traits:['has got a fish','likes burgers','can play football'],last:'next to the bookcase',pos:'p3',pronoun:'HIM'},
 {name:'LUCY',traits:['has got a cat','likes apples','can swim'],last:"near the teacher's desk",pos:'p4',pronoun:'HER'}];
const memory=[
 {q:'Where is the blue book?',a:['ON THE TABLE','UNDER THE CHAIR','NEXT TO THE WINDOW'],ok:0},
 {q:'What is under the table?',a:['A CAT','A BALL','A TOY BOX'],ok:1},
 {q:'What colour is the chair?',a:['BLUE','YELLOW','RED'],ok:2},
 {q:'Is there a cat behind the chair?',a:['YES','NO'],ok:0}];
const scans=[
 {name:'BALL',a:['A BALL','A MOON','AN ORANGE'],ok:0,x:27,y:43},
 {name:'BOOK',a:['A BOX','A BOOK','A TABLET'],ok:1,x:47,y:45},
 {name:'BANANA',a:['A CAMERA','A BANANA','A SHOE'],ok:1,x:66,y:40},
 {name:'CAMERA',a:['A CAMERA','A RADIO','A CLOCK'],ok:0,x:31,y:67},
 {name:'ROBOT',a:['A ROBOT','A DOLL','A MONSTER'],ok:0,x:62,y:67}];
const dbTasks=[
 {person:0,fact:0,q:"CHECK MILO'S PET",context:"Milo says: 'My pet can run. It can't fly and it can't swim.'",a:['A DOG','A BIRD','A FISH'],ok:0},
 {person:0,fact:1,q:"CHECK MILO'S LUNCH",context:"Milo has got cheese, tomato and bread. What does he make?",a:['PIZZA','SOUP','ICE CREAM'],ok:0},
 {person:0,fact:2,q:"CHECK MILO'S CLUB",context:"Milo is in the pool. Complete his answer: 'Yes, I ___." ,a:['CAN SWIM','CAN FLY','HAVE SWIM'],ok:0},
 {person:1,fact:0,q:"CHECK ZOE'S PET",context:"Zoe says: 'It is small. It has got four legs. It says meow.'",a:['A CAT','A FISH','A BIRD'],ok:0},
 {person:1,fact:1,q:"CHECK ZOE'S SNACK",context:"Zoe chooses the long yellow fruit. What does she like?",a:['BANANAS','APPLES','CARROTS'],ok:0},
 {person:1,fact:2,q:"CHECK ZOE'S JOURNEY",context:"Zoe has got a helmet and two wheels. What can she do?",a:['RIDE A BIKE','PLAY THE PIANO','SWIM'],ok:0},
 {person:2,fact:0,q:"CHECK BEN'S PET",context:"Ben says: 'My pet lives in water. It hasn't got legs.'",a:['A FISH','A DOG','A CAT'],ok:0},
 {person:2,fact:1,q:"CHECK BEN'S LUNCH",context:"Ben has got bread, cheese and salad. Which food is it?",a:['A BURGER','A BANANA','A CAKE'],ok:0},
 {person:2,fact:2,q:"CHECK BEN'S TEAM",context:"Ben has got a ball. He kicks it into a goal. What can he do?",a:['PLAY FOOTBALL','RIDE A BIKE','PLAY THE GUITAR'],ok:0},
 {person:3,fact:0,q:"CHECK LUCY'S PET",context:"Lucy says: 'It sleeps on my chair and it likes milk.'",a:['A CAT','A FISH','A HORSE'],ok:0},
 {person:3,fact:1,q:"CHECK LUCY'S SNACK",context:"Lucy's fruit is red or green. It grows on a tree.",a:['APPLES','BANANAS','POTATOES'],ok:0},
 {person:3,fact:2,q:"CHECK LUCY'S CLUB",context:"Lucy is in the water. She has got goggles. What can she do?",a:['SWIM','FLY','SKATE'],ok:0}];
const rooms=[
 {name:'CLASSROOM',pos:'0% 0%',x:10,y:18},{name:'PLAYROOM',pos:'50% 0%',x:38,y:11},{name:'LIBRARY',pos:'100% 0%',x:69,y:15},
 {name:'GARDEN',pos:'0% 100%',x:9,y:66},{name:'KITCHEN',pos:'50% 100%',x:61,y:84},{name:'MUSIC ROOM',pos:'100% 100%',x:90,y:67},
 {name:'ART ROOM',pos:'0% 50%',x:37,y:54,extra:true},{name:'HALL',pos:'50% 50%',x:92,y:28,extra:true},{name:'GYM',pos:'100% 50%',x:36,y:88,extra:true}];
const mapTasks=[
 {q:'START WHERE THERE ARE TWO WINDOWS AND A BLUE DESK.',ok:0},
 {q:'NEXT: FIND A RED CHAIR AND A TOY TRAIN.',ok:1},
 {q:'GO TO THE PLACE WITH A GREEN TABLE AND MANY BOOKS.',ok:2},
 {q:'FOLLOW THE TRACK TO A BALL NEAR A BICYCLE.',ok:3},
 {q:'FIND THREE BLUE CUPS AND SOME BANANAS.',ok:4},
 {q:'THE LAST PRINT IS NEAR A PIANO AND A DRUM.',ok:5}];
mapTasks.push(
 {q:'GO TO THE ROOM WITH PAINT AND PICTURES.',ok:6},
 {q:'GO TO THE PLACE WITH MANY DOORS AND A CLOCK.',ok:7},
 {q:'FIND THE ROOM WITH A BALL AND A BASKET.',ok:8});
const glitchTasks=[
 {q:'can / a fish / swim / ?',a:['CAN A FISH SWIM?','A FISH CAN SWIM?','SWIM A FISH CAN?'],ok:0},
 {q:'Choose the correct sentence.',a:['SHE HAVE GOT A CAT.','SHE HAS GOT A CAT.','SHE GOT HAS A CAT.'],ok:1},
 {q:'Where is the ball?',a:['IT IS UNDER THE TABLE.','IT ARE TABLE.','UNDER IS BALL.'],ok:0},
 {q:'Choose the correct question.',a:['CAN HE RIDE A BIKE?','HE CAN RIDE A BIKE?','CAN RIDE HE BIKE?'],ok:0}];

function beep(good=true){if(!state.sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=good?620:180;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}}
function showScreen(n){state.screen=n;$$('.screen').forEach((s,i)=>s.classList.toggle('active',i===n));scrollTo({top:0});if(n===1)startMemory();if(n===2)renderScan();if(n===3)renderDatabase();if(n===4){if(!state.mapRoute)state.mapRoute=[0,...[1,2,3,4,5,6,7,8].sort(()=>Math.random()-.5).slice(0,4)];renderMap()}if(n===5)renderGlitch();if(n===6)renderFinal();if(n===7)celebrate()}
$$('[data-next]').forEach(b=>b.onclick=()=>showScreen(state.screen+1));$$('[data-go]').forEach(b=>b.onclick=()=>showScreen(+b.dataset.go));
$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'SOUND ON':'SOUND OFF';beep()};
function setAnswers(box,items,ok,onDone,onWrong=()=>{}){const correct={text:items[ok],i:ok},wrong=items.map((text,i)=>({text,i})).filter(x=>x.i!==ok).sort(()=>Math.random()-.5),slot=state.answerTurn%items.length;state.answerTurn++;const mixed=[...wrong];mixed.splice(slot,0,correct);box.innerHTML=mixed.map(x=>`<button class="answer-btn" data-i="${x.i}">${x.text}</button>`).join('');$$('.answer-btn',box).forEach(b=>b.onclick=()=>{const right=+b.dataset.i===ok;beep(right);b.classList.add(right?'correct':'wrong');if(right){$$('.answer-btn',box).forEach(x=>x.disabled=true);onDone(b)}else{onWrong(b);b.classList.add('shake');setTimeout(()=>{b.classList.remove('shake');b.classList.remove('wrong')},350)}})}
function startMemory(){state.memory=0;$('#memoryView').classList.remove('hidden');$('#memoryQuiz').classList.add('hidden');$('#memoryNext').classList.add('hidden');let t=12;$('#lookTimer').textContent=t;clearInterval(window.lookClock);window.lookClock=setInterval(()=>{t--;$('#lookTimer').textContent=t;if(t<=0){clearInterval(window.lookClock);showMemoryQuestion()}},1000)}
function showMemoryQuestion(){$('#memoryView').classList.add('hidden');$('#memoryQuiz').classList.remove('hidden');const x=memory[state.memory];$('#memoryCount').textContent=`QUESTION ${state.memory+1} OF ${memory.length}`;$('#memoryQuestion').textContent=x.q;$('#memoryFeedback').textContent='';setAnswers($('#memoryAnswers'),x.a,x.ok,()=>{$('#memoryFeedback').textContent='Good detective work!';setTimeout(()=>{state.memory++;if(state.memory<memory.length)showMemoryQuestion();else $('#memoryNext').classList.remove('hidden')},700)})}
let lights=2;$('#lightsBtn').onclick=()=>{if(lights<1)return;lights--;$('#lightsBtn small').textContent=`${lights} left`;$('#memoryView').classList.remove('hidden');$('#memoryQuiz').classList.add('hidden');setTimeout(()=>{if(state.memory<memory.length)showMemoryQuestion()},3500)};$('#memoryNext').onclick=()=>awardClue(0,2);
function renderScan(){const scanner=$('#scanner'),lens=$('#scanLens'),hotspots=$('#scanHotspots');$('#scanNum').textContent=state.scanFound.size;$('#scanNext').classList.toggle('hidden',state.scanFound.size<scans.length);hotspots.innerHTML=scans.map((x,i)=>state.scanFound.has(i)?'':`<i class="scan-target" style="left:${x.x}%;top:${x.y}%"></i>`).join('');$('#scanTray').innerHTML=[...state.scanFound].map(i=>`<article style="background-position:${scans[i].x}% ${scans[i].y}%"><b>${scans[i].name}</b></article>`).join('')||'<span>EMPTY</span>';if(!scanner.dataset.ready){const move=e=>{const r=scanner.getBoundingClientRect(),x=Math.max(0,Math.min(r.width,e.clientX-r.left)),y=Math.max(0,Math.min(r.height,e.clientY-r.top));lens.style.left=x+'px';lens.style.top=y+'px';lens.style.backgroundSize=`${r.width}px ${r.height}px`;lens.style.backgroundPosition=`${-x+55}px ${-y+55}px`};scanner.onpointermove=move;scanner.onpointerenter=()=>lens.classList.add('active');scanner.onpointerleave=()=>lens.classList.remove('active');scanner.onclick=e=>{const r=scanner.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*100,py=(e.clientY-r.top)/r.height*100,candidates=scans.map((s,i)=>({i,d:Math.hypot((s.x-px)*1.4,s.y-py)})).filter(x=>!state.scanFound.has(x.i)).sort((a,b)=>a.d-b.d);if(candidates[0]&&candidates[0].d<9)openScan(candidates[0].i);else $('#scanFeedback').textContent='Only static here. Move the scanner and try another spot.'};scanner.dataset.ready='1'}if(state.scanFound.size===0){$('#scanQuestion').textContent='Find a shape. Tap it.';$('#scanAnswers').classList.add('hidden')}}
function openScan(i){if(state.scanFound.has(i))return;state.scanCurrent=i;const x=scans[i];$('#scanQuestion').textContent='WHAT IS THIS OBJECT?';$('#scanFeedback').textContent='';$('#scanAnswers').classList.remove('hidden');setAnswers($('#scanAnswers'),x.a,x.ok,()=>{state.scanFound.add(i);$('#scanFeedback').textContent=`${x.name}. EVIDENCE TAG READY.`;setTimeout(()=>{renderScan();if(state.scanFound.size<5)$('#scanQuestion').textContent='Find another shape.'},700)},()=>$('#scanFeedback').textContent='Move the scanner and look again.')}
$('#scanNext').onclick=()=>awardClue(1,3);
function openPortrait(i,checked=3){const p=people[i];$('#bigPortrait').className=`big-portrait ${p.pos}`;$('#bigName').textContent=p.name;$('#bigTraits').innerHTML=p.traits.map((t,n)=>`<span>${n<checked?t:'CHECK THE STORY'}</span>`).join('');$('#portraitModal').classList.remove('hidden')}
function cardHTML(p,i,checked=0){return `<article class="suspect-card ${checked<3?'locked':''}"><button class="portrait ${p.pos}" data-zoom="${i}" data-checked="${checked}" aria-label="Look closely at ${p.name}"><i class="zoom-lens"></i></button><div><h3>${p.name}</h3><small class="fact-count">${checked} / 3 FACTS</small><div class="traits">${p.traits.map((t,n)=>`<span class="${n<checked?'fact-open':''}">${n<checked?t:'CHECK THE STORY'}</span>`).join('')}</div></div></article>`}
function bindZoom(){$$('[data-zoom]').forEach(b=>b.onclick=e=>{e.stopPropagation();openPortrait(+b.dataset.zoom,b.dataset.checked===undefined?3:+b.dataset.checked)})}
function renderDatabase(){const checked=people.map((_,i)=>Math.max(0,Math.min(3,state.db-i*3)));$('#suspectCards').innerHTML=people.map((p,i)=>cardHTML(p,i,checked[i])).join('');bindZoom();$('#taskDots').innerHTML=dbTasks.map((_,i)=>`<i class="${i<state.db?'done':''}"></i>`).join('');$('#interviewContinue').classList.add('hidden');if(state.db>=dbTasks.length){$('#interviewLabel').textContent='INTERVIEWS COMPLETE';$('#dbQuestion').textContent='ALL STORIES ARE ON THE CASE BOARD.';$('#dbContext').textContent='Use these facts with the four clues in the final deduction.';$('#dbAnswers').innerHTML='';$('#dbNext').classList.remove('hidden');return}const x=dbTasks[state.db];$('#interviewLabel').textContent=`INTERVIEW ${String(state.db+1).padStart(2,'0')} / 12 · ${people[x.person].name}`;$('#dbQuestion').textContent=x.q;$('#dbContext').textContent=x.context;$('#dbFeedback').textContent='';setAnswers($('#dbAnswers'),x.a,x.ok,()=>{$('#dbFeedback').textContent=`FACT ${x.fact+1} FOR ${people[x.person].name} IS READY. Ask the class to say the full sentence.`;$('#interviewContinue').classList.remove('hidden')})}$('#interviewContinue').onclick=()=>{state.db++;renderDatabase()};$('#dbNext').onclick=()=>awardClue(2,4);
function renderFootprints(){const trail=$('#footprintTrail');trail.innerHTML='';for(let n=1;n<state.mapHistory.length;n++){const a=rooms[state.mapHistory[n-1]],b=rooms[state.mapHistory[n]],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx*12,dy*7),steps=Math.max(2,Math.floor(d/38)),angle=Math.atan2(dy*7,dx*12)*180/Math.PI;for(let k=1;k<steps;k++){const foot=document.createElement('i'),t=k/steps;foot.style.left=`${a.x+dx*t}%`;foot.style.top=`${a.y+dy*t}%`;foot.style.transform=`translate(-50%,-50%) rotate(${angle+90}deg) translateX(${k%2?'-7px':'7px'})`;trail.append(foot)}}}
function renderMap(){const map=$('#roomMap');map.querySelectorAll('.room').forEach(x=>x.remove());rooms.forEach((r,i)=>{const b=document.createElement('button');b.className='room map-node';b.setAttribute('aria-label',`Open ${r.name}`);b.style.left=r.x+'%';b.style.top=r.y+'%';b.style.backgroundImage=`url('assets/${r.extra?'map-locations-extra':'map-locations'}.png')`;b.style.backgroundSize=r.extra?'300% 100%':'300% 200%';b.style.backgroundPosition=r.pos;b.dataset.room=i;b.onclick=()=>openLocation(i);map.append(b)});const target=state.mapRoute?.[state.map];$('#mapQuestion').textContent=target===undefined?'THE ROUTE IS COMPLETE!':mapTasks[target].q;$('#trailCount').textContent=`${state.map} / 5`;renderFootprints();if(state.map>=5)$('#mapNext').classList.remove('hidden')}
function openLocation(i){state.mapCurrent=i;const r=rooms[i],big=$('#bigLocation');big.style.backgroundImage=`url('assets/${r.extra?'map-locations-extra':'map-locations'}.png')`;big.style.backgroundSize=r.extra?'300% 100%':'300% 200%';big.style.backgroundPosition=r.pos;$('#locationName').textContent=r.name;$('#locationModal').classList.remove('hidden')}
function chooseRoom(i){if(state.map>=5)return;const right=i===state.mapRoute[state.map];beep(right);if(!right){$('#mapFeedback').textContent='Not this place. Inspect another location.';$('#locationModal').classList.add('hidden');return}const r=rooms[i],pawn=$('#detectivePawn');state.mapHistory.push(i);pawn.style.left=r.x+'%';pawn.style.top=r.y+'%';pawn.classList.add('walking');setTimeout(()=>pawn.classList.remove('walking'),900);$('#locationModal').classList.add('hidden');$('#mapFeedback').innerHTML=state.map===4?'<b>EVIDENCE FOUND!</b> A bicycle tyre mark is here.':`The route now reaches ${r.name.toLowerCase()}.`;state.map++;setTimeout(renderMap,900)}
$('#chooseLocation').onclick=()=>chooseRoom(state.mapCurrent);$('#closeLocation').onclick=()=>$('#locationModal').classList.add('hidden');$('#locationModal').onclick=e=>{if(e.target===$('#locationModal'))$('#locationModal').classList.add('hidden')};$('#mapNext').onclick=()=>showScreen(5);
function updateMonster(){const scale=Math.max(.42,.72-state.glitch*.09+state.glitchDanger*.16);$('#monster').style.setProperty('--scale',scale);$('#distanceLabel').textContent=state.glitchDanger>=2?'VERY CLOSE':state.glitchDanger===1?'CLOSER':state.glitch>=2?'FAR AWAY':'FAR';$('#glitchMeter').style.width=`${state.glitch/glitchTasks.length*100}%`}
function renderGlitch(){$$('#cctvRecovery i').forEach((tile,i)=>tile.classList.toggle('clear',i<state.glitch));$('.glitch-field').classList.toggle('file-ready',state.glitch>=glitchTasks.length);if(state.glitch>=glitchTasks.length){$('#glitchQuestion').textContent='THE PHOTO IS CLEAR. WHAT CAN YOU SEE?';$('#glitchAnswers').innerHTML='';$('#glitchFeedback').textContent='A bicycle wheel. A helmet with a banana sticker. A purple piece of fabric.';$('#monster').classList.add('glitch-gone');$('#glitchNext').classList.remove('hidden');$('#glitchMeter').style.width='100%';return}const x=glitchTasks[state.glitch];$('#glitchQuestion').textContent=x.q;$('#glitchFeedback').textContent=`PHOTO PART ${state.glitch+1} OF 4`;updateMonster();setAnswers($('#glitchAnswers'),x.a,x.ok,()=>{$('#glitchFeedback').textContent='ONE MORE PART IS CLEAR.';state.glitch++;state.glitchDanger=Math.max(0,state.glitchDanger-1);updateMonster();setTimeout(renderGlitch,750)},()=>{state.glitchDanger=Math.min(2,state.glitchDanger+1);$('#glitchFeedback').textContent='THE FILE BREAKS AGAIN. TRY ONCE MORE.';updateMonster()})}$('#glitchNext').onclick=()=>awardClue(3,6);
function renderBoard(){$('#boardCount').textContent=`${state.clues} / 4`;$('#boardStatus').textContent=state.clues===4?'READY FOR THE FINAL DEDUCTION':`${4-state.clues} CLUES TO FIND`;$('#boardClues').innerHTML=clues.map((clue,i)=>`<article class="board-clue c${i+1} ${i<state.clues?'pinned':'locked'}">${i===3&&i<state.clues?'<img src="assets/camera-photo.png" alt="Camera evidence">':''}<small>CLUE ${i+1}</small><b>${i<state.clues?clue:'?'}</b></article>`).join('')}
function awardClue(index,next){state.clues=Math.max(state.clues,index+1);$('#progressText').textContent=`CLUES: ${state.clues} / 4`;$('#progressFill').style.width=`${state.clues*25}%`;$('#clueNumber').textContent=`CLUE #${index+1}`;$('#clueText').textContent=clues[index];state.pendingNext=next;renderBoard();$('#clueModal').classList.remove('hidden');beep()}$('#keepClue').onclick=()=>{$('#clueModal').classList.add('hidden');state.advanceAfterBoard=true;$('#caseBoard').classList.remove('hidden')};$('#closeClue').onclick=()=>$('#keepClue').click();
function renderFinal(){$('#clueStrip').innerHTML=clues.map((c,i)=>`<div class="mini-clue"><small>CLUE ${i+1}</small>${c.replace('THE PERSON ','')}</div>`).join('');$('#finalSuspects').innerHTML=people.map((p,i)=>`<article class="final-card ${state.excluded.has(i)?'excluded':''} ${state.selected===i?'selected':''}" data-i="${i}" data-not="NOT ${p.pronoun}"><button class="portrait ${p.pos}" data-zoom="${i}" aria-label="Look closely at ${p.name}"><i class="zoom-lens"></i></button><h3>${p.name}</h3><div class="final-traits">${[...p.traits,p.last].map(t=>`<span>${t}</span>`).join('')}</div><div class="deduction-actions"><button class="mark-btn" data-mark="${i}">${state.excluded.has(i)?'PUT BACK':'NOT '+p.pronoun}</button><button class="choose-btn" data-choose="${i}">CHOOSE</button></div></article>`).join('');bindZoom();$$('[data-mark]').forEach(b=>b.onclick=()=>{const i=+b.dataset.mark;if(state.excluded.has(i))state.excluded.delete(i);else{state.excluded.add(i);if(state.selected===i)state.selected=null}renderFinal()});$$('[data-choose]').forEach(b=>b.onclick=()=>{const i=+b.dataset.choose;if(state.excluded.has(i))state.excluded.delete(i);state.selected=i;renderFinal()});$('#accuseBtn').disabled=state.selected===null}
$('#resetMarks').onclick=()=>{state.excluded.clear();state.selected=null;renderFinal()};$('#accuseBtn').onclick=()=>{if(state.selected===1)showScreen(7);else{beep(false);$('.final-card.selected').classList.add('shake');setTimeout(()=>$('.final-card.selected')?.classList.remove('shake'),400)}};
function celebrate(){const colors=['#f5b942','#34d6cb','#ef6a5b','#fff'];$('#confetti').innerHTML=Array.from({length:35},(_,i)=>`<span style="left:${Math.random()*100}%;background:${colors[i%4]};animation-delay:${Math.random()*3}s"></span>`).join('');beep()}
$('#playAgain').onclick=()=>location.reload();
$('#closePortrait').onclick=()=>$('#portraitModal').classList.add('hidden');$('#portraitModal').onclick=e=>{if(e.target===$('#portraitModal'))$('#portraitModal').classList.add('hidden')};
$('#boardBtn').onclick=()=>{state.advanceAfterBoard=false;renderBoard();$('#caseBoard').classList.remove('hidden')};$('#closeBoard').onclick=()=>{$('#caseBoard').classList.add('hidden');if(state.advanceAfterBoard){state.advanceAfterBoard=false;showScreen(state.pendingNext)}};$('#caseBoard').onclick=e=>{if(e.target===$('#caseBoard'))$('#closeBoard').click()};renderBoard();

/* WOW upgrade: investigation-first interactions */
const interrogationPrompts=['HAVE YOU GOT A PET?','WHAT DO YOU LIKE?','CAN YOU DO IT?','WHERE ARE YOU?'];
const interrogationLabels=['PET','LIKES','CAN','LAST SEEN'];
function allFacts(p){return [p.traits[0],p.traits[1],p.traits[2],p.last]}
cardHTML=function(p,i,checked=0){const facts=allFacts(p);return '<article class="suspect-card interrogation-card '+(checked<4?'locked':'')+'"><button class="portrait '+p.pos+'" data-zoom="'+i+'" data-checked="'+checked+'" aria-label="Look closely at '+p.name+'"><i class="zoom-lens"></i></button><div><h3>'+p.name+'</h3><small class="fact-count">'+checked+' / 4 FACTS</small><div class="traits">'+facts.map((t,n)=>'<span class="'+(n<checked?'fact-open':'')+'">'+(n<checked?t:interrogationLabels[n]+': ?')+'</span>').join('')+'</div></div></article>'}
renderDatabase=function(){const total=16,person=Math.min(3,Math.floor(state.db/4)),fact=state.db%4,checked=people.map((_,i)=>Math.max(0,Math.min(4,state.db-i*4)));$('#suspectCards').innerHTML=people.map((p,i)=>cardHTML(p,i,checked[i])).join('');bindZoom();$('#taskDots').innerHTML=Array.from({length:16},(_,i)=>'<i class="'+(i<state.db?'done':'')+'"></i>').join('');$('#interviewContinue').classList.add('hidden');if(state.db>=total){$('#interviewLabel').textContent='INTERROGATIONS COMPLETE';$('#dbQuestion').textContent='ALL FOUR CASE FILES ARE READY.';$('#dbContext').textContent='Open the Case Board and compare every fact.';$('#dbAnswers').innerHTML='';$('#dbNext').classList.remove('hidden');return}const p=people[person],answers=['YES! I HAVE GOT '+p.traits[0].replace('has got ','').toUpperCase()+'.','I '+p.traits[1].toUpperCase()+'.','YES! I '+p.traits[2].toUpperCase()+'.','I AM '+p.last.toUpperCase()+'.'];$('#interviewLabel').textContent='QUESTION '+(fact+1)+' / 4 · '+p.name;$('#dbQuestion').textContent=interrogationPrompts[fact];$('#dbContext').textContent='Ask the question together. Then reveal the answer.';$('#dbFeedback').textContent='';$('#dbAnswers').innerHTML='<button class="answer-btn ask-reveal">ASK / REVEAL ANSWER</button>';$('.ask-reveal').onclick=()=>{$('#dbContext').textContent=answers[fact];$('#dbFeedback').textContent='FACT CARD REVEALED.';$('#interviewContinue').classList.remove('hidden')};$('#interviewContinue').onclick=()=>{state.db++;renderDatabase()}}
function startInspect(){$('#lightsBtn').classList.add('hidden');$('#memoryQuiz').classList.add('hidden');$('#memoryView').classList.add('hidden');$('#inspectScene').classList.remove('hidden');$('#memoryNext').classList.add('hidden')}
$('#memoryNext').onclick=()=>state.inspectFound?awardClue(0,2):startInspect();
const inspectFrame=$('#inspectFrame'),inspectLens=$('#inspectLens');
if(inspectFrame){inspectFrame.onpointermove=e=>{const r=inspectFrame.getBoundingClientRect();inspectLens.style.left=(e.clientX-r.left)+'px';inspectLens.style.top=(e.clientY-r.top)+'px'};$$('[data-spot]').forEach(b=>b.onclick=()=>{if(b.dataset.spot==='window'){state.inspectFound=true;b.classList.add('found');$('#inspectFeedback').innerHTML='<b>EVIDENCE FOUND!</b><br>A small muddy mark is near the window.';$('#memoryNext').textContent='PIN EVIDENCE #01';$('#memoryNext').classList.remove('hidden')}else{$('#inspectFeedback').textContent='Nothing useful here. Keep looking.';b.classList.add('checked')}})}
const boardAnchors={clue:[[180,205],[1020,195],[205,565],[1000,565]],person:[[420,345],[550,315],[680,345],[810,325]]};
renderBoard=function(){$('#boardCount').textContent=state.clues+' / 4';$('#boardStatus').textContent=state.boardSelected===null?'SELECT EVIDENCE, THEN A PERSON':'EVIDENCE '+(state.boardSelected+1)+' SELECTED';$('#boardClues').innerHTML=clues.map((clue,i)=>'<article data-board-clue="'+i+'" class="board-clue evidence-polaroid c'+(i+1)+' '+(i<state.clues?'pinned':'locked')+' '+(state.boardSelected===i?'selected':'')+'"><div class="evidence-thumb e'+(i+1)+'">'+(i===3&&i<state.clues?'<img src="assets/cctv-evidence-v2.png" alt="CCTV evidence details">':'')+'</div><small>EVIDENCE '+String(i+1).padStart(2,'0')+'</small><b>'+(i<state.clues?clue:'?')+'</b></article>').join('');$('#boardSuspects').innerHTML=people.map((p,i)=>'<div class="board-person '+p.pos+' '+(state.ruled.has(i)?'ruled-out':'')+'" data-board-person="'+i+'"><i></i><span>'+p.name+'</span><button data-rule="'+i+'">'+(state.ruled.has(i)?'RESTORE':'RULE OUT')+'</button></div>').join('');$('#boardStrings').innerHTML=[...state.connections].map(key=>{const parts=key.split('-').map(Number),a=boardAnchors.clue[parts[0]],b=boardAnchors.person[parts[1]];return '<path class="live-string" d="M'+a[0]+' '+a[1]+' Q '+((a[0]+b[0])/2)+' '+(a[1]-45)+' '+b[0]+' '+b[1]+'"/>'}).join('');$$('[data-board-clue]').forEach(el=>el.onclick=()=>{const i=+el.dataset.boardClue;if(i<state.clues){state.boardSelected=state.boardSelected===i?null:i;renderBoard()}});$$('[data-board-person]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-rule]')||state.boardSelected===null)return;const key=state.boardSelected+'-'+el.dataset.boardPerson;state.connections.has(key)?state.connections.delete(key):state.connections.add(key);renderBoard()});$$('[data-rule]').forEach(b=>b.onclick=e=>{e.stopPropagation();const i=+b.dataset.rule;state.ruled.has(i)?state.ruled.delete(i):state.ruled.add(i);renderBoard()})}
renderBoard();
const originalShowScreen=showScreen;
showScreen=function(n){originalShowScreen(n);if(n>1&&n<7){const names={2:'X-RAY LAB',3:'INTERROGATION ROOM',4:'FOLLOW THE FOOTPRINTS',5:'CCTV LAB',6:'FINAL CASE BOARD'};$('#transitionTitle').textContent=names[n];$('#transitionCard').classList.remove('hidden');setTimeout(()=>$('#transitionCard').classList.add('hidden'),850)}}
$('#glitchNext').onclick=()=>$('#twistModal').classList.remove('hidden');
$('#openTwistBoard').onclick=()=>{$('#twistModal').classList.add('hidden');awardClue(3,6)};
function beginReveal(){state.revealStep=0;$('#revealModal').classList.remove('hidden');$('#revealChecks').innerHTML='';$('#revealTitle').textContent='CHECKING EVIDENCE...';$('#revealContinue').textContent='CHECK EVIDENCE 01'}
$('#accuseBtn').onclick=()=>{if(state.selected===1)beginReveal();else{beep(false);if($('.final-card.selected'))$('.final-card.selected').classList.add('shake');setTimeout(()=>{if($('.final-card.selected'))$('.final-card.selected').classList.remove('shake')},400)}};
$('#revealContinue').onclick=()=>{if(state.revealStep<clues.length){const line=document.createElement('div');line.className='reveal-check';line.textContent=clues[state.revealStep]+' ✓';$('#revealChecks').append(line);state.revealStep++;$('#revealContinue').textContent=state.revealStep===4?'SHOW WHO MOVED IT':'CHECK EVIDENCE '+String(state.revealStep+1).padStart(2,'0')}else{$('#revealModal').classList.add('hidden');showScreen(7)}};
openPortrait=function(i,checked=4){const p=people[i],facts=allFacts(p);$('#bigPortrait').className='big-portrait '+p.pos;$('#bigName').textContent=p.name;$('#bigTraits').innerHTML=facts.map((t,n)=>'<span>'+(n<checked?t:'CHECK THE STORY')+'</span>').join('');$('#portraitModal').classList.remove('hidden')};